name = "subscription-manager"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 绑定 KV 命名空间
[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
id = "a2827759fb114eb682d59a426c4c85b5"

# 自动任务（每分钟执行检查）
[triggers]
crons = ["* * * * *"]

# 环境变量
[vars]
ENVIRONMENT = "production"
